# Generated by Django 4.2.15 on 2024-10-07 15:42

import apps.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.CharField(
                default=apps.categories.models.generate_short_uuid,
                editable=False,
                max_length=4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
