# Generated by Django 4.2.15 on 2024-10-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
