# Generated by Django 4.2.15 on 2024-10-04 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
