# Generated by Django 4.2.15 on 2024-10-04 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
