# Generated by Django 4.2.15 on 2024-10-05 06:14

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_article_created_at_alter_article_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.CharField(
                default=apps.blog.models.generate_short_id,
                editable=False,
                max_length=4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
