# Generated by Django 4.2.15 on 2024-10-07 16:11

import apps.articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.CharField(
                default=apps.articles.models.generate_nanoid,
                editable=False,
                max_length=4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
